Import('BaseEnv')

env = BaseEnv.Clone()
env['CPPPATH'] = ['.']
env.EnableQt4Modules(['QtCore'])
env['LIBS']+=['qjson']

Sources = ['baseconverters.cpp','servicesmanager.cpp',
           'jsonserializer.cpp','devicemanager.cpp']

Headers = ['QRemoteSignal','absservice.h','baseconverters.h',
           'servicesmanager.h','baseexception.h',
           'message.h','absmessageserializer.h',
           'jsonserializer.h','serializationexceptions.h',
           'devicemanager.h']

libs = [
   env.SharedLibrary('QRemoteSignal',Sources),
   env.StaticLibrary('#tests/QRemoteSignal',Sources)
]

Pc = env.Config('QRemoteSignal.pc.in')
env.AlwaysBuild(Pc)

env.Install(env['CONFIG']['PREFIX_LIB'],libs)
env.Install(env['CONFIG']['PREFIX_INC'],Headers)
env.Install(env['CONFIG']['PREFIX_PC'],Pc)

BaseEnv['QRemoteSignalStatic'] = libs[1]
