Import('env')

env['CPPPATH'] += ['.','..','../common']

Sources=['printserver.cpp','server.cpp','../common/connectionprocessor.cpp']

Sources += env.QRSService('../print.xml')

env.Program('printserver',Sources)