Import('env')

env['CPPPATH'] += ['.','../common']

Sources=['printserver.cpp','server.cpp','../common/connectionprocessor.cpp']

Sources += env.QRSService('../common/print.xml')

env.Program('printserver',Sources)