Import('env')

CommonSources = ['serializerstestsuit.cpp','messagetesttools.cpp']

results = []
results.append( env.Program('#tests/JsonSerializerTestSuit',['json.cpp']+CommonSources) )
results.append( env.Program('#tests/QDataStreamSerializerTestSuit',['qdatastream.cpp']+CommonSources) )
results.append( env.Program('#tests/QDataStreamSerializerTestSuit_3.3',['qdatastream_3.3.cpp']+CommonSources) )
results.append( env.Program('#tests/QDataStreamSerializerTestSuit_4.0',['qdatastream_4.0.cpp']+CommonSources) )
results.append( env.Program('#tests/QDataStreamSerializerTestSuit_4.2',['qdatastream_4.2.cpp']+CommonSources) )
results.append( env.Program('#tests/QDataStreamSerializerTestSuit_4.3',['qdatastream_4.3.cpp']+CommonSources) )
results.append( env.Program('#tests/QDataStreamSerializerTestSuit_4.4',['qdatastream_4.4.cpp']+CommonSources) )
results.append( env.Program('#tests/QDataStreamSerializerTestSuit_4.5',['qdatastream_4.5.cpp']+CommonSources) )

Return('results')
