Import('env')

CommonSources = ['serializerstestsuit.cpp','messagetesttools.cpp']

results = []
results.append( env.Program('#tests/JsonSerializerTestSuit',['json.cpp']+CommonSources) )
results.append( env.Program('#tests/QDataStreamSerializerTestSuit',['qdatastream.cpp']+CommonSources) )

Return('results')
