Import('BaseEnv')

env = BaseEnv.Clone()
env['CPPPATH']=['.']
env.EnableQt4Modules(['QtCore','QtXml','QtXmlPatterns'])

Resources=['templates.qrc']
Sources=['xic.cpp','qtextserializer.cpp','interfacedocument.cpp',
         'interfacecompiler.cpp','argvparser.cpp']
Sources += env.Qrc(Resources)

env.AlwaysBuild( env.Config('config.h.in') )
BaseEnv['XIC'] = env.Program('xic',Sources)[0]
env.Install(env['CONFIG']['PREFIX_BIN'],BaseEnv['XIC'])
