Import('BaseEnv')

env = BaseEnv.Clone()
env['CPPPATH']=['.']
env.EnableQt4Modules(['QtCore','QtXml','QtXmlPatterns'])

Resources=['templates.qrc']
Sources=['xic.cpp','qtextserializer.cpp','interfacedocument.cpp',
         'interfacecompiler.cpp','xicconfig.cpp']
Sources += env.Qrc(Resources)

env.AlwaysBuild( env.Config('config.h.in') )
xic = env.Program('xic',Sources)
env.Install(env['CONFIG']['PREFIX_BIN'],xic)
