import os

env = Environment(ENV=os.environ)
env.Tool('qt4')
env.EnableQt4Modules(['QtCore','QtNetwork'])
env.Tool('qrs')
env['CXXFILESUFFIX']='.cpp'

Export('env')

SConscript('server/SConscript')
SConscript('client/SConscript')
