import os

env = Environment(tools=[],ENV=os.environ)
if env['PLATFORM'] == 'win32':
   env.Tool('mingw')
else:
   env.Tool('default')
env.Tool('qt4')
env.EnableQt4Modules(['QtCore','QtNetwork'])
env.Tool('qrs')
env['CXXFILESUFFIX']='.cpp'

Export('env')

SConscript('server/SConscript')
SConscript('client/SConscript')
